### PR TITLE
Add awesome lint as the test used for continuous integration

### PR DESCRIPTION
**Pull request by ChristianMurphy**
https://github.com/sindresorhus/awesome-lint

### CODE REVIEW

**Comment by wooorm** [comment]
This is nice!

I personally don’t agree with their list-item-indent rule, but I don’t think it’s possible to turn their rules off right?

**Comment by wooorm** [comment]
Also, I’d prefer to have both btw, remark catches some other things!

**Comment by ChristianMurphy** [comment]
It can be configured only through the programmatic API AFAIK.
https://github.com/sindresorhus/awesome-lint/blob/7a52420c3fc543bf5b21cba9c41a3c94afa5a058/index.js#L16-L33
It may be easier to apply the awesome lint configuration to remark https://github.com/sindresorhus/awesome-lint/blob/7a52420c3fc543bf5b21cba9c41a3c94afa5a058/config.js#L3-L56

**Comment by wooorm** [comment]
Ahhh, in that case, keep it as a dependency, and add `awesome-lint/config` + `preset-wooorm` to the plugins in `package.json`? That should overwrite their styles with my preferences, but still include their custom rules!

**Comment by ChristianMurphy** [comment]
Updated to apply the awesome lint config to remark along side preset woorm

**Comment by wooorm** [comment]
Ah, if you do the config first, and the preset later, it’ll pick up on our style.
I didn’t think about the fact that it checks all files, including `contributing.md` :(

**Comment by ChristianMurphy** [comment]
:thinking: does unified support glob based patterns? https://eslint.org/docs/user-guide/configuring#configuration-based-on-glob-patterns

**Comment by wooorm** [comment]
No, it doesn’t unfortunately, but you could run remark on all files with preset-wooorm, and then the config + preset-wooorm on just the readme.md. Two different runs, and inline the config instead of having it in `remarkConfig`.

That’s something a new thing that would deal better with files may potentially work on though 😎

**Comment by wooorm** [comment]
Sorry I totally missed this PR when I was working on GH-5! 😬

**Pull request closed without merging**
